### ISSUE TITLE
MemoryError

### ISSUE THREAD

**Issue by w4kfu** [serpilliere/elfesteem#16]
By trying to open a ELF file on Windows python x86-64, I got a MemoryError at this line : https://github.com/serpilliere/elfesteem/blob/master/elfesteem/strpatchwork.py#L25

    >C:\Python27x64\python.exe
    ...
    >>> from elfesteem import *
    >>> elf_init.ELF(open("test-i386", "rb").read())
    Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    File "C:\Python27x64\lib\site-packages\elfesteem\elf_init.py", line 756, in __init__
        self.parse_content()
    File "C:\Python27x64\lib\site-packages\elfesteem\elf_init.py", line 771, in parse_content
        self.sh = SHList(self, self.sex, self.size)
    File "C:\Python27x64\lib\site-packages\elfesteem\elf_init.py", line 473, in __init__
        s.parse_content(sex, size)
    File "C:\Python27x64\lib\site-packages\elfesteem\elf_init.py", line 309, in parse_content
        c = c[12 + namesz + descsz:]
    File "C:\Python27x64\lib\site-packages\elfesteem\strpatchwork.py", line 25, in __getitem__
        s.extend(array("B", self.paddingbyte * (end - l)))
    MemoryError

It seems that on linux `sys.maxsize == sys.maxint` :

    linux-machine$ python
    ...
    >>> import sys
    >>> sys.maxsize
    9223372036854775807
    >>> sys.maxint
    9223372036854775807

But not on Windows:
    
    windows-machine>C:\Python27x64\python.exe
    ...
    >>> import sys
    >>> sys.maxint
    2147483647
    >>> sys.maxsize
    9223372036854775807L
    
Also maxint has been removed in python3 see https://docs.python.org/3.1/whatsnew/3.0.html#integers.

**Comment by serpilliere** [comment]
Great: thanks for the tip!
